### ISSUE TITLE
Issue with swapping Quote for Base token 

### ISSUE THREAD

**Issue by 0xSSDD** [ElasticSwap/elasticswap-sdk#113]
**Describe the bug**
Mostly on mainnet pools, calls to `swapQuoteTokenForBaseToken` are being reverted with `MathLib: INSUFFICIENT_BASE_TOKEN_QTY`. This could be a possible bug in the SDK, since the app uses the SDK to calculate and then calls the contracts.

Increasing slippage helps, but that shouldn't be necessary. All things equal, if the slippage is at zero any high impact transaction should still work. Slippage is meant to be the amount beyond the expected price impact. We're only seeing it in the pools with lower amount of assets. 1inch isn't having the issue, so they're calculating it correctly.

**Reference**
* List of transactions that have failed in TIC/USDC pool: https://etherscan.io/txs?a=0x79274bf95e05f0e858ab78411f3ebe85909e4f76&f=1
* List of transactions that have failed in AMPL/USDC pool: https://etherscan.io/txs?a=0xa0c5aa50ce3cc69b1c478d8235597bc0c51dfdab&f=1

One of the failed transactions in the TIC/USDC pool: https://dashboard.tenderly.co/tx/mainnet/0xfe104eb24f1a006217f3346a6d3f33b940ec1c82e54a6df7a754c1ea31f1ce05
<img width="1115" alt="Screenshot 2022-08-14 at 12 36 45" src="https://user-images.githubusercontent.com/49087443/184531113-103087e0-b3ad-44c1-9749-6f975a2b5799.png">

**Comment by 0xean** [comment]
@0xSSDD -I am little unclear on the below quote - 

> All things equal, if the slippage is at zero any high impact transaction should still work.

If you create a transaction, and while it is waiting to be mined, the price changes, the call would revert. So zero slippage would definitely be a problem. 

To debug if something is actually wrong here, we would probably need to know roughly the time the transaction was created and the state of the pool (X and Y) at that moment and then the state of the pools at the time the transaction was mined (X and Y)

The smaller pools will experience more slippage, so not quite sure there is an actual issue here or expected behavior.

**Comment by 0xean** [comment]
<img width="441" alt="Screen Shot 2022-08-15 at 6 58 45 AM" src="https://user-images.githubusercontent.com/15096737/184639304-9a9f98c0-c0f2-449b-855b-7f850449e942.png">

**Comment by 0xSSDD** [comment]
> To debug if something is actually wrong here, we would probably need to know roughly the time the transaction was created and the state of the pool (X and Y) at that moment and then the state of the pools at the time the transaction was mined (X and Y)

Currently doing something very similar, will be using an archive node to get the state of the pool just before the transaction and will check if the SDK returns numbers that are causing the revert. If so it could be a SDK issue, if not, I suspect it could be a front-end issue. 

>  Increasing the amount of default slippage for small pools or providing a warning to users who have tight slippage in small pools may help.

I think this is most likely the fix to the issue once the SDK is ruled out

**Comment by 0xSSDD** [comment]
The bug has been disproved, as ca be seen at https://github.com/ElasticSwap/elasticswap-sdk/pull/115
