### ISSUE TITLE
[Feature] Multicall

### ISSUE THREAD

**Issue by dmvt** [ElasticSwap/elasticswap-sdk#43]
# Description / Motivation

MakerDAO's Multicall contract provides a way to make a single read call to a blockchain node that in turn calls multiple functions across multiple other contracts and returns their data. Using this contract in the SDK for read requests that do not contain a specific blockTag (see: [ethers.js contract function calls overrides section](https://docs.ethers.io/v5/api/contract/contract/#Contract-functionsCall)) would greatly decrease the number of network roundtrips and significantly speed up the frontend.

## Resources

https://snowtrace.io/address/0x8755b94F88D120AB2Cc13b1f6582329b067C760d#code
https://github.com/makerdao/multicall

## Potential approach

Every contract class (example: [StakingPools.mjs](https://github.com/ElasticSwap/elasticswap-sdk/blob/development/src/staking/StakingPools.mjs)) falls back on the [contract function in the SDK](https://github.com/ElasticSwap/elasticswap-sdk/blob/development/src/index.mjs#L404). All of these classes have (or should have) both [contract](https://github.com/ElasticSwap/elasticswap-sdk/blob/development/src/staking/StakingPools.mjs#L59) and [readonlyContract](https://github.com/ElasticSwap/elasticswap-sdk/blob/development/src/staking/StakingPools.mjs#L70) getters. I've considered having readonly contract intercept requests (all requests return promises) with no overrides, collect them for some tuneable amount of time (100ms perhaps to start) and then pass them off to multicall. When multicall returns, the responses could be split out again and used to resolve the original request promises.

# Definition of complete

When calling multiple read only contract methods in quick succession there is only one call made to the blockchain node.

# Example Scenario

The load of the staking page is very heavy (or rather the load of its data)
https://github.com/ElasticSwap/elasticswap-app/blob/development/src/stores/global.js#L34

# Developer Notes

* Yarn-link the Svelte app and the SDK node package
* Use node v16 for both
* Make sure `yarn --version` correctly reports `1.x` for both
* `yarn dev` must be run for both the SDK and the APP

# Test Networks

Use fuji or avalanche

May as well be avalanche since you're just doing reads.

https://docs.elasticswap.org/avalanche <-- instructions if you don't have avalanche c-chain added yet

**Comment by meglio** [comment]
## updateStakingPools() - blockchain calls breakdown

Below is a rough breakdown of all calls to blockchain that `updateStakingPools()` entails directly or indirectly.
`elasticswap-app/src/stores/global.js/updateStakingPools()`

```
1. In app, valuePerToken()
           valuePerTimeToken()
           sdk.stakingPools.getPoolToken(poolId),
 => in sdk, this.contract.getPoolToken(this.toNumber(poolId))

2. In app, sdk.stakingPools.getPoolRewardWeight(poolId)
 => in sdk, this.contract.getPoolRewardWeight(this.toNumber(poolId))

3. In app, sdk.stakingPools.totalRewardWeight()
=> in sdk, this.contract.totalRewardWeight()

(promises for steps 1. and 4. are started simultaneously in the app)
4. In app, valuePerTic()
           slpAddress = await sdk.stakingPools.getPoolToken(SLP_POOL_ID)
           await usdcContract.balanceOf(slpAddress),
           await ticContract.balanceOf(slpAddress)
           Note: balanceOf() is an ether's meta method, we'll have to convert it to actual correct ABI methods
=> in sdk, toBigNumber(await this.provider.getBalance(key), 18)

5. In app, visibility()
           hasTokenOrStake()
           const address = await sdk.stakingPools.getPoolToken(poolId); (duplicates step 1)
           const contract = sdk.contract({ address });
           5.1. sdk.stakingPools.getStakeTotalDeposited(sdk.account, poolId),
           5.2. toBigNumber(await contract.balanceOf(sdk.account), 18) (duplicates step 4)
           Note: 5.1. and 5.2. promises are started in parallel

6. In app, sdk.stakingPools.getPoolRewardWeight(poolId) (duplicates step 2)

7. In app, sdk.stakingPools.getAPR(poolId)
 => in sdk, this.getPoolRewardRate(poolId)
            this.getPoolTotalDeposited(poolId)
            this.getPoolToken(poolId) (Duplicates step 1)

8. In app, sdk.stakingPools.getPoolToken(poolId) (duplicates step 1)

9. In app, sdk.stakingPools.getTVL(poolId, valuePer) (valuePer comes from step 1)
 => in sdk, await this.contract.getPoolTotalDeposited(this.toNumber(poolId)) (duplicates step 8)
            await this.contract.getStakeTotalDeposited(account, this.toNumber(poolId))

10. (if sdk.account, otherwise toBigNumber(0))
In app, sdk.stakingPools.getStakeTotalDeposited(sdk.account, poolId),
 => in sdk, this.contract.getStakeTotalDeposited(account, this.toNumber(poolId))

11. (if sdk.account, toBigNumber(0))
In app, sdk.stakingPools.getStakeTotalUnclaimed(sdk.account, poolId),
 => in sdk, await this.contract.getStakeTotalUnclaimed(account, this.toNumber(poolId))

12. (if sdk.account, otherwise toBigNumber(0))
    Note: Promises 12.1 and 12.2 started simultaneously
12.1. In app, tokenContract.balanceOf(sdk.account)
      Note: balanceOf() is an ether's meta method
12.2. In app, tokenContract.allowance(sdk.account, sdk.stakingPools.address)
 => in sdk, await ERC20Token.allowance(ownerAddress, spenderAddress)

```
